import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'fr' | 'ar' | 'kab';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation & Common
    'nav.services': 'Services',
    'nav.materials': 'Materials Marketplace',
    'nav.machinery': 'Hire Machinery',
    'nav.logistics': 'Site Logistics',
    'nav.consultancy': 'Consultancy',
    'nav.company': 'Company',
    'nav.story': 'Our Story',
    'nav.safety': 'Safety',
    'nav.newsroom': 'Newsroom',
    'nav.business': 'Business',
    'nav.register_shop': 'Register Shop',
    'nav.work_with_us': 'Work with Us',
    'nav.careers': 'Careers',
    'nav.support': 'Support',
    'nav.help_center': 'Help Center',
    'nav.contact': 'Contact Us',
    'nav.login': 'Log In',
    'nav.signup': 'Sign Up',
    'nav.dashboard': 'Dashboard',
    'nav.delivery_history': 'Delivery History',
    'nav.my_orders': 'My Orders',
    'nav.shops': 'Shops',
    'nav.users': 'Users',
    'nav.products': 'Products',
    'nav.live_tracking': 'Live Tracking',
    'nav.messages': 'Messages',
    'nav.settings': 'Settings',
    'nav.sign_out': 'Sign Out',
    'nav.system': 'System',
    'nav.new_order': 'New Order',
    'nav.profile': 'Profile',
    'nav.search_placeholder': 'Search orders, drivers or customers...',
    'nav.notifications': 'Notifications',
    'nav.live_updates': 'Live Updates',
    'nav.no_notifications': 'No notifications yet',
    'nav.view_all_activity': 'View All Activity',

    // Home / Hero Section
    'hero.badge': 'Verified Official Release',
    'hero.title': 'Download Jeebha Mobile Super-App.',
    'hero.subtitle': 'We have completed construction testing. The web platform is now official! Use the native Jeebha Android client for the fastest load-tracking, live logistics updates, and material orders.',
    'hero.spec_file': 'File Name',
    'hero.spec_size': 'File Size',
    'hero.spec_version': 'Version',
    'hero.spec_os': 'OS Support',
    'hero.btn_download': 'Download APK Now',
    'hero.btn_playstore': 'Google Play Store',
    'hero.download_success': 'Direct APK Download triggered successfully!',
    'hero.welcome_title': 'What would you like today?',
    'hero.book_load': 'Book a load',
    'hero.materials_option': 'Order Materials & Aggregate',
    'hero.logistics_option': 'Book Site Logistics Transport',
    'hero.register_option': 'Register Shop as Supplier',
    'hero.got_it': 'Got It, Thanks!',
    'hero.become_partner': 'Become a Partner Now',
    'hero.driver_active': 'Active Driver Registration Active',
    'hero.driver_sub': 'Earn daily income. Track deliveries. Be your own boss.',

    // Onboarding / Installation Steps
    'install.guide_title': 'Android Install Guide',
    'install.steps_badge': '3 Simple Steps',
    'install.step1_title': 'Get the Installer',
    'install.step1_desc': 'The direct download of "jeebha.apk" starts automatically. If it did not start, use the download button above.',
    'install.step2_title': 'Permit Unknown Sources',
    'install.step2_desc': 'Go to Settings > Security > Enable "Install Unknown Apps" for your web browser (Chrome, Samsung Internet, etc.) to authorize the package.',
    'install.step3_title': 'Start Earning & Ordering',
    'install.step3_desc': 'Open the downloaded file, completed in seconds, and click "Install". Create your official account directly inside the mobile app!',
    'install.security_promise': 'SECURITY PROMISE',
    'install.security_text': 'Our application is packed without bloatware, tracker elements, or third-party ads. Fully verified safe for builder, driver and manager workspaces.',

    // Downloader Dialog / Modal
    'modal.install_mobile': 'Installing Jeebha Mobile',
    'modal.prod_release': 'Official Production Release (v1.0.0)',
    'modal.fast_download': 'Fast Direct Download Active',
    'modal.download_desc': 'Downloading jeebha.apk to Android downloads folder',
    'modal.restart_btn': 'Restart Download',
    'modal.step1_title': 'Download Started',
    'modal.step1_desc': 'The direct APK file is downloading. If the download did not start, ',
    'modal.step1_click': 'click here to retry',
    'modal.step2_title': 'Enable Unknown Sources',
    'modal.step2_desc': 'Go to Settings > Security > Install Unknown Apps and toggle "Allow from this source" for your browser if prompted.',
    'modal.step3_title': 'Open & Install',
    'modal.step3_desc': 'Tap on the completed download notification or open the downloaded "jeebha.apk" file to start working immediately.',
    'modal.protect_notice': 'Jeebha is officially verified and secure. If Google Play Protect shows a popup, click "Install anyway" to proceed with the official release.',
    'modal.super_app': 'North Africa Super-App',

    // Dashboard Customizations
    'dash.title': 'Jeebha Workspace is now Mobile.',
    'dash.subtitle': 'For security, real-time geofencing, and encrypted site transactions, our desktop testing is complete. Access the official network exclusively via the Android App.',
    'dash.specs_title': 'App Specifications',
    'dash.compat_released': 'Released',
    'dash.compat_size': 'File Size',
    'dash.compat_os': 'Android OS',
    'dash.compat_cpu': 'CPU Arch',
    'dash.compat_perm': 'Permissions',
    'dash.compat_perm_val': 'Location, Camera',
    'dash.compat_safe': 'Safe & Certified',
    'dash.compat_safe_desc': 'Every package is cryptographically compiled and verified secure to run safely on all construction site hardware.',
    'dash.seed_hub': 'Demo Hub Active',
    'dash.seed_desc': 'You have full access to explore Jeebha. Start by seeding the marketplace.',
    'dash.seed_btn': 'Seed Marketplace',

    // Booking
    'booking.departure': 'Departure',
    'booking.departure_placeholder': 'Choose departure location',
    'booking.destination': 'Destination',
    'booking.destination_placeholder': 'Choose destination site',
    'booking.searching_map': 'Searching world map...',
    'booking.efficiency_desc': 'Efficient logistics, designed for your convenience.',

    // Services Landing Features
    'service.materials_delivery': 'MATERIALS DELIVERY',
    'service.peace_of_mind': 'Build with total peace of mind',
    'service.quick_easy_title': 'Quick & Easy',
    'service.quick_easy_desc': 'One click on the app is all it takes to get materials at your location. Anytime, anywhere.',
    'service.secure_title': 'Secure',
    'service.secure_desc': 'Our suppliers are verified and the deliveries are geolocalized, so you can build in complete safety.',
    'service.right_price_title': 'The Right Price',
    'service.right_price_desc': 'Rates adjusted to the service you choose, displayed in advance, no annoying surprises!',
    'service.site_ready': 'Site Ready',

    // Become Partner & Recruitment
    'partner.become_partner_sub': 'BECOME A PARTNER',
    'partner.earn_money': 'Become a supplier and earn money',
    'partner.own_boss': 'Be your own boss',
    'partner.own_boss_desc': 'Work whenever you want from the comfort of your shop, with just a tap of the screen.',
    'partner.easy_use': 'Easy to use',
    'partner.easy_use_desc': 'The Jeebha supplier app is all you need to get load requests in your area.',
    'partner.talents': 'Talents',
    'partner.talents_desc': 'Join one of the fast growing construction startups in Africa. Backed by the founders of Google, Airbnb & Spotify.',
    'partner.see_openings': 'See openings',
    'partner.partners': 'Partners',
    'partner.partners_desc': "Either you're a supplier or a trucker, start earning money with Jeebha in a matter of days.",
    'partner.businesses': 'Businesses',
    'partner.businesses_desc': 'Are you a construction company or site owner? Join Jeebha by registering your business and start saving.',
    'partner.get_listed': 'Get listed now',
    'partner.future_building': 'The Future of Building',
    'partner.future_desc': 'Download the app and transform your site management today.',

    // Stats
    'stats.title_part1': 'Jeebha is growing fast. ',
    'stats.title_part2': 'Really fast.',
    'stats.tons': 'tons delivered',
    'stats.partners': 'partners',
    'stats.employees': 'employees',
    'stats.cities': 'cities covered',

    // Footer
    'footer.tagline': "Building the digital infrastructure for Africa's construction industry. Transparent, data-driven, and local.",
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',

    // Map Picker Details
    'booking.select_departure': 'Select Departure Location',
    'booking.select_destination': 'Select Destination Location',
    'map.instructions': 'Click anywhere on the map to drop a pin',
    'map.confirm': 'Confirm Selection',
    'map.selected_location': 'Selected Location',
    'map.fetching': 'Fetching...',
    'map.use_location': 'Use this location',
    'hero.welcome_greet': 'Welcome,',
    'hero.the_app': 'THE JEEBHA APP',
    'store.download': 'Download',
    'store.android_apk': 'Android APK',
    'store.ios_build': 'iOS Build',
  },
  fr: {
    // Navigation & Common
    'nav.services': 'Services',
    'nav.materials': 'Marché des matériaux',
    'nav.machinery': 'Louer des machines',
    'nav.logistics': 'Logistique de chantier',
    'nav.consultancy': 'Conseils',
    'nav.company': 'Entreprise',
    'nav.story': 'Notre histoire',
    'nav.safety': 'Sécurité',
    'nav.newsroom': 'Actualités',
    'nav.business': 'Affaires',
    'nav.register_shop': 'Inscrire un magasin',
    'nav.work_with_us': 'Travailler avec nous',
    'nav.careers': 'Carrières',
    'nav.support': 'Support',
    'nav.help_center': 'Centre d\'aide',
    'nav.contact': 'Contactez-nous',
    'nav.login': 'Connexion',
    'nav.signup': 'S\'inscrire',
    'nav.dashboard': 'Tableau de bord',
    'nav.delivery_history': 'Historique de livraison',
    'nav.my_orders': 'Mes commandes',
    'nav.shops': 'Magasins',
    'nav.users': 'Utilisateurs',
    'nav.products': 'Produits',
    'nav.live_tracking': 'Suivi en direct',
    'nav.messages': 'Messages',
    'nav.settings': 'Paramètres',
    'nav.sign_out': 'Se déconnecter',
    'nav.system': 'Système',
    'nav.new_order': 'Nouvelle commande',
    'nav.profile': 'Profil',
    'nav.search_placeholder': 'Rechercher des commandes, des chauffeurs ou des clients...',
    'nav.notifications': 'Notifications',
    'nav.live_updates': 'Mises à jour en direct',
    'nav.no_notifications': 'Aucune notification pour le moment',
    'nav.view_all_activity': 'Voir toute l\'activité',

    // Home / Hero Section
    'hero.badge': 'Version officielle validée',
    'hero.title': 'Téléchargez la Super-App Mobile Jeebha.',
    'hero.subtitle': 'Nous avons terminé les tests de construction. La plateforme web est devenue officielle! Utilisez le client Android natif Jeebha pour un suivi de charge ultra-rapide, logistique de chantier et commande de matériaux.',
    'hero.spec_file': 'Nom du fichier',
    'hero.spec_size': 'Taille du fichier',
    'hero.spec_version': 'Version',
    'hero.spec_os': 'Support OS',
    'hero.btn_download': 'Télécharger l\'APK maintenant',
    'hero.btn_playstore': 'Google Play Store',
    'hero.download_success': 'Téléchargement direct de l\'APK lancé avec succès!',
    'hero.welcome_title': 'Que désirez-vous aujourd\'hui?',
    'hero.book_load': 'Réserver un camion de chargement',
    'hero.materials_option': 'Commander des matériaux et granulats',
    'hero.logistics_option': 'Réserver un transport logistique de chantier',
    'hero.register_option': 'Inscrire un magasin comme fournisseur',
    'hero.got_it': 'Compris, merci!',
    'hero.become_partner': 'Devenir partenaire maintenant',
    'hero.driver_active': 'Enregistrement de chauffeur actif',
    'hero.driver_sub': 'Gagnez un revenu quotidien. Suivez vos livraisons. Soyez votre propre patron.',

    // Onboarding / Installation Steps
    'install.guide_title': 'Guide d\'installation Android',
    'install.steps_badge': '3 ÉTAPES ETAPE PAR ETAPE',
    'install.step1_title': 'Obtenir l\'installateur',
    'install.step1_desc': 'Le téléchargement direct du fichier "jeebha.apk" commence automatiquement. S\'il n\'a pas démarré, cliquez sur le bouton ci-dessus.',
    'install.step2_title': 'Autoriser les sources inconnues',
    'install.step2_desc': 'Allez dans Paramètres > Sécurité > Activer "Installer des applications de sources inconnues" pour votre navigateur (Chrome, Samsung Internet, etc.).',
    'install.step3_title': 'Commencez à gagner et commander',
    'install.step3_desc': 'Ouvrez le fichier téléchargé en quelques secondes, puis cliquez sur "Installer". Créez votre compte officiel directement sur l\'application mobile!',
    'install.security_promise': 'ENGAGEMENT DE SÉCURITÉ',
    'install.security_text': 'Notre application est compilée sans logiciels publicitaires ou traceurs tiers. Entièrement vérifiée et sécurisée pour les chantiers, chauffeurs et gestionnaires.',

    // Downloader Dialog / Modal
    'modal.install_mobile': 'Installation de Jeebha Mobile',
    'modal.prod_release': 'Version de production stable (v1.0.0)',
    'modal.fast_download': 'Téléchargement direct actif',
    'modal.download_desc': 'Téléchargement de jeebha.apk dans votre dossier Téléchargements',
    'modal.restart_btn': 'Relancer le téléchargement',
    'modal.step1_title': 'Téléchargement démarré',
    'modal.step1_desc': 'L\'APK direct est en cours de téléchargement. Si le téléchargement n\'a pas démarré, ',
    'modal.step1_click': 'cliquez ici pour réessayer',
    'modal.step2_title': 'Activer les sources inconnues',
    'modal.step2_desc': 'Allez dans Paramètres > Sécurité > Installer des applications inconnues et activez l\'option pour ce navigateur.',
    'modal.step3_title': 'Ouvrir & Installer',
    'modal.step3_desc': 'Appuyez sur la notification de fin de téléchargement ou ouvrez le fichier "jeebha.apk" téléchargé pour lancer l\'application immédiatement.',
    'modal.protect_notice': 'Jeebha est officiellement vérifiée et sécurisée. Si Google Play Protect affiche une alerte, cliquez sur "Installer quand même" pour continuer.',
    'modal.super_app': 'Super-App pour l\'Afrique du Nord',

    // Dashboard Customizations
    'dash.title': 'L\'espace Jeebha est maintenant mobile.',
    'dash.subtitle': 'Pour la sécurité, le géorepérage en temps réel et les transactions cryptées sur les chantiers, les tests web sont clos. Accédez au réseau officiel uniquement via l\'application Android.',
    'dash.specs_title': 'Spécifications de l\'application',
    'dash.compat_released': 'Publié',
    'dash.compat_size': 'Taille du fichier',
    'dash.compat_os': 'Système Android',
    'dash.compat_cpu': 'Arch CPU',
    'dash.compat_perm': 'Permissions',
    'dash.compat_perm_val': 'Localisation, Caméra',
    'dash.compat_safe': 'Sécurisé & Certifié',
    'dash.compat_safe_desc': 'Chaque package est cryptographiquement signé et certifié sûr pour fonctionner sur l\'ensemble des équipements de chantier.',
    'dash.seed_hub': 'Hub de démo actif',
    'dash.seed_desc': 'Vous avez un accès complet pour explorer Jeebha. Commencez par alimenter le marché.',
    'dash.seed_btn': 'Alimenter le marché',

    // Booking
    'booking.departure': 'Départ',
    'booking.departure_placeholder': 'Choisir le lieu de départ',
    'booking.destination': 'Destination',
    'booking.destination_placeholder': 'Choisir le chantier de destination',
    'booking.searching_map': 'Recherche sur la carte du monde...',
    'booking.efficiency_desc': 'Une logistique efficace, conçue pour votre commodité.',

    // Services Landing Features
    'service.materials_delivery': 'LIVRAISON DE MATÉRIAUX',
    'service.peace_of_mind': 'Construisez en toute sérénité',
    'service.quick_easy_title': 'Simple & Rapide',
    'service.quick_easy_desc': 'Un seul clic sur l\'application suffit pour recevoir vos matériaux sur votre chantier. N\'importe quand, n\'importe où.',
    'service.secure_title': 'Sécurisé',
    'service.secure_desc': 'Nos fournisseurs sont vérifiés et les livraisons sont géolocalisées, pour construire en toute sécurité.',
    'service.right_price_title': 'Le Juste Prix',
    'service.right_price_desc': 'Tarifs adaptés au service choisi, affichés à l\'avance, sans mauvaises surprises !',
    'service.site_ready': 'Chantier Prêt',

    // Become Partner & Recruitment
    'partner.become_partner_sub': 'DEVENIR PARTENAIRE',
    'partner.earn_money': 'Devenez fournisseur et gagnez de l\'argent',
    'partner.own_boss': 'Soyez votre propre patron',
    'partner.own_boss_desc': 'Travaillez quand vous voulez depuis le confort de votre magasin, d\'un simple geste sur l\'écran.',
    'partner.easy_use': 'Facile à utiliser',
    'partner.easy_use_desc': 'L\'application fournisseur Jeebha est tout ce dont vous avez besoin pour obtenir des demandes dans votre zone.',
    'partner.talents': 'Talents',
    'partner.talents_desc': 'Rejoignez l\'une des startups de construction à la croissance la plus rapide d\'Afrique. Soutenue par les fondateurs de Google, Airbnb et Spotify.',
    'partner.see_openings': 'Voir les postes ouverts',
    'partner.partners': 'Partenaires',
    'partner.partners_desc': "Que vous soyez fournisseur ou transporteur, commencez à gagner de l'argent avec Jeebha en quelques jours.",
    'partner.businesses': 'Entreprises',
    'partner.businesses_desc': 'Vous êtes une entreprise de construction ou un propriétaire de chantier ? Rejoignez Jeebha en enregistrant votre entreprise et commencez à économiser.',
    'partner.get_listed': 'Inscrivez-vous maintenant',
    'partner.future_building': 'L\'Avenir de la Construction',
    'partner.future_desc': 'Téléchargez l\'application et transformez la gestion de votre chantier dès aujourd\'hui.',

    // Stats
    'stats.title_part1': 'Jeebha grandit vite. ',
    'stats.title_part2': 'Très vite.',
    'stats.tons': 'tonnes livrées',
    'stats.partners': 'partenaires pourvu',
    'stats.employees': 'employés engagés',
    'stats.cities': 'villes couvertes',

    // Footer
    'footer.tagline': "Bâtir l'infrastructure numérique pour l'industrie de la construction en Afrique. Transparent, axé sur les données et local.",
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Conditions',

    // Map Picker Details
    'booking.select_departure': 'Sélectionner le lieu de départ',
    'booking.select_destination': 'Sélectionner la destination',
    'map.instructions': 'Cliquez n\'importe où sur la carte pour placer un repère',
    'map.confirm': 'Confirmer la sélection',
    'map.selected_location': 'Position sélectionnée',
    'map.fetching': 'Recherche...',
    'map.use_location': 'Utiliser cette position',
    'hero.welcome_greet': 'Bienvenue,',
    'hero.the_app': "L'APPLICATION JEEBHA",
    'store.download': 'Télécharger',
    'store.android_apk': 'APK Android',
    'store.ios_build': 'Version iOS',
  },
  ar: {
    // Navigation & Common
    'nav.services': 'الخدمات',
    'nav.materials': 'سوق مواد البناء',
    'nav.machinery': 'تأجير الآليات',
    'nav.logistics': 'لوجستيات الموقع',
    'nav.consultancy': 'الاستشارات',
    'nav.company': 'الشركة',
    'nav.story': 'قصتنا',
    'nav.safety': 'السلامة والأمان',
    'nav.newsroom': 'غرفة الأخبار',
    'nav.business': 'الأعمال والشركاء',
    'nav.register_shop': 'تسجيل متجر',
    'nav.work_with_us': 'اعمل معنا',
    'nav.careers': 'الوظائف',
    'nav.support': 'الدعم والمساعدة',
    'nav.help_center': 'مركز المساعدة',
    'nav.contact': 'اتصل بنا',
    'nav.login': 'تسجيل الدخول',
    'nav.signup': 'إنشاء حساب',
    'nav.dashboard': 'لوحة التحكم',
    'nav.delivery_history': 'سجل التوصيل',
    'nav.my_orders': 'طلباتي',
    'nav.shops': 'المتاجر',
    'nav.users': 'المستخدمين',
    'nav.products': 'المنتجات',
    'nav.live_tracking': 'التتبع المباشر',
    'nav.messages': 'الرسائل',
    'nav.settings': 'الإعدادات',
    'nav.sign_out': 'تسجيل الخروج',
    'nav.system': 'النظام',
    'nav.new_order': 'طلب جديد',
    'nav.profile': 'الملف الشخصي',
    'nav.search_placeholder': 'البحث عن طلبات، سائقين أو عملاء...',
    'nav.notifications': 'الإشعارات',
    'nav.live_updates': 'تحديثات مباشرة',
    'nav.no_notifications': 'لا توجد إشعارات بعد',
    'nav.view_all_activity': 'عرض كل النشاطات',

    // Home / Hero Section
    'hero.badge': 'إصدار رسمي معتمد وموثوق',
    'hero.title': 'تحميل تطبيق جيبها للهواتف الذكية.',
    'hero.subtitle': 'لقد أكملنا مرحلة الاختبارات الميدانية. المنصة الإلكترونية أصبحت رسمية الآن! استخدم تطبيق جيبها المخصص لأجهزة الأندرويد للاستفادة من أسرع نظام لتتبع الشحنات، اللوجستيات المباشرة وطلب المواد.',
    'hero.spec_file': 'اسم الملف',
    'hero.spec_size': 'حجم الملف',
    'hero.spec_version': 'الإصدار',
    'hero.spec_os': 'دعم النظام',
    'hero.btn_download': 'تحميل ملف APK الآن',
    'hero.btn_playstore': 'متجر جوجل بلاي',
    'hero.download_success': 'تم تشغيل تحميل ملف APK المباشر بنجاح!',
    'hero.welcome_title': 'ماذا تريد أن تطلب اليوم؟',
    'hero.book_load': 'حجز شاحنة نقل حمولات',
    'hero.materials_option': 'طلب مواد بناء وحصى ومستلزمات',
    'hero.logistics_option': 'حجز خدمات النقل واللوجستيات للموقع',
    'hero.register_option': 'تسجيل متجرك وتوريد المواد للموقع',
    'hero.got_it': 'حسناً، شكراً!',
    'hero.become_partner': 'انضم كشريك الآن',
    'hero.driver_active': 'تسجيل السائقين نشط حالياً',
    'hero.driver_sub': 'احصل على دخل يومي ثابت. تتبع شحناتك. كن مدير نفسك.',

    // Onboarding / Installation Steps
    'install.guide_title': 'دليل تثبيت أندرويد',
    'install.steps_badge': '٣ خطوات بسيطة',
    'install.step1_title': 'الحصول على ملف التثبيت',
    'install.step1_desc': 'يبدأ تحميل ملف "jeebha.apk" المباشر بشكل تلقائي. إذا لم يبدأ، اضغط على زر التحميل بالأعلى.',
    'install.step2_title': 'السماح بالمصادر غير المعروفة',
    'install.step2_desc': 'الذهاب إلى الإعدادات > الأمان > تفعيل خيار "تثبيت التطبيقات من مصادر غير معروفة" لمتصفح الإنترنت الخاص بك.',
    'install.step3_title': 'ابدأ الكسب والطلب',
    'install.step3_desc': 'افتح الملف المحمل بعد اكتماله في ثوانٍ، واضغط "تثبيت". أنشئ حسابك الرسمي داخل التطبيق مباشرة في خطوات!',
    'install.security_promise': 'ضمان أمن المعلومات والأمان',
    'install.security_text': 'تم برمجة وتعبئة التطبيق كلياً دون أي برمجيات ضارة أو إعلانات من أطراف ثالثة. آمن تماماً لسائقي النقل بالمواقع والمهندسين والمدراء.',

    // Downloader Dialog / Modal
    'modal.install_mobile': 'تثبيت جيبها للموبايل',
    'modal.prod_release': 'الإصدار الرسمي والنهائي المستقر (v1.0.0)',
    'modal.fast_download': 'التحميل المباشر والسريع نشط',
    'modal.download_desc': 'يتم تحميل ملف jeebha.apk إلى مجلد التنزيلات الخاص بجهازك',
    'modal.restart_btn': 'إعادة بدء التحميل',
    'modal.step1_title': 'بدأ التحميل الآن',
    'modal.step1_desc': 'يتم تنزيل ملف APK المباشر. إذا لم يبدأ التنزيل تلقائياً، ',
    'modal.step1_click': 'اضغط هنا للمحاولة مجدداً',
    'modal.step2_title': 'تفعيل تثبيت التطبيقات المجهولة',
    'modal.step2_desc': 'لو سمحت اذهب للإعدادات > الأمان > تثبيت التطبيقات المجهولة وقم بتفعيل الخيار للمتصفح الحالي.',
    'modal.step3_title': 'الفتح والتثبيت',
    'modal.step3_desc': 'اضغط على إشعار اكتمال التنزيل أو افتح ملف jeebha.apk الذي تم تنزيله للتثبيت الفوري.',
    'modal.protect_notice': 'منصة جيبها معتمدة وآمنة بالكامل. إذا ظهر لك تنبيه من Google Play Protect، اضغط "التثبيت على أي حال" للمضي قدماً في التثبيت الآمن والنهائي.',
    'modal.super_app': 'تطبيق البناء الشامل لشمال أفريقيا',

    // Dashboard Customizations
    'dash.title': 'مساحة عمل جيبها أصبحت للهواتف الذكية.',
    'dash.subtitle': 'لأسباب تتعلق بالسلامة والأمن الرقمي، والتتبع الجغرافي المباشر وحماية المعاملات، انتهت مرحلة الاختبارات على الويب. استخدم التطبيق لتسجيل الدخول الفعلي.',
    'dash.specs_title': 'مواصفات التطبيق الفنية',
    'dash.compat_released': 'تاريخ النشر',
    'dash.compat_size': 'حجم الملف',
    'dash.compat_os': 'نظام التشغيل المطلوب',
    'dash.compat_cpu': 'المعالج المدعوم',
    'dash.compat_perm': 'صلاحيات التطبيق',
    'dash.compat_perm_val': 'الموقع الجغرافي، الكاميرا',
    'dash.compat_safe': 'آمن ومعتمد بالكامل',
    'dash.compat_safe_desc': 'تم فحص وترميز الحزمة إلكترونياً لضمان تشغيلها المثالي والآمن على جميع الأجهزة العاملة في مواقع البناء والتوريد.',
    'dash.seed_hub': 'بيئة العرض النشطة',
    'dash.seed_desc': 'لديك حق الوصول الكامل لاستكشاف جيبها. ابدأ بتغذية سوق المنتجات بالبيانات.',
    'dash.seed_btn': 'تغذية قاعدة بيانات السوق',

    // Booking
    'booking.departure': 'نقطة الانطلاق',
    'booking.departure_placeholder': 'اختر موقع الانطلاق',
    'booking.destination': 'وجهة التوصيل',
    'booking.destination_placeholder': 'اختر موقع ورشة البناء المستلمة',
    'booking.searching_map': 'جاري البحث في خريطة العالم...',
    'booking.efficiency_desc': 'سوق خدمات لوجستية ونقل ذكي، مصمم لتلبية كافة احتياجاتك بسهولة.',

    // Services Landing Features
    'service.materials_delivery': 'توصيل مواد البناء',
    'service.peace_of_mind': 'قم بالبناء والتعمير براحة بال تامة',
    'service.quick_easy_title': 'سهل وسريع',
    'service.quick_easy_desc': 'كبسة زر واحدة على تطبيق جيبها كافية للحصول على كل المواد لموقعك، في أي وقت وأي مكان.',
    'service.secure_title': 'آمن وموثوق',
    'service.secure_desc': 'موردونا معتمدون ومفحوصون والشحنات متتبعة جغرافياً لتضمن الأمان الكامل لموقعك.',
    'service.right_price_title': 'السعر العادل والصحيح',
    'service.right_price_desc': 'أسعار دقيقة ومدروسة حسب الخدمة المحددة، تظهر لك مسبقاً دون أي مفاجآت ورسوم مخفية!',
    'service.site_ready': 'الموقع جاهز للبناء',

    // Become Partner & Recruitment
    'partner.become_partner_sub': 'كن شريكاً معنا',
    'partner.earn_money': 'سجل كمالك شاحنة أو مورد بناء وابدأ بجني الأرباح',
    'partner.own_boss': 'كن مدير نفسك',
    'partner.own_boss_desc': 'اعمل في الأوقات التي تناسبك بحرية كاملة ومن راحة متجرك بلمسة زر على الشاشة.',
    'partner.easy_use': 'بسيط الاستخدام',
    'partner.easy_use_desc': 'تطبيق جيبها للشركاء هو كل ما تحتاجه لتلقي طلبات النقل والخدمات في منطقتك الجغرافية.',
    'partner.talents': 'المواهب والكفاءات',
    'partner.talents_desc': 'انضم إلى إحدى أسرع الشركات الناشئة نمواً في قطاع التشييد والبناء في أفريقيا، بدعم كبار المستثمرين دولياً.',
    'partner.see_openings': 'استعرض الوظائف المتاحة',
    'partner.partners': 'الشركاء والسائقين',
    'partner.partners_desc': 'سواء كنت شريكاً توريدياً أو سائق شاحنة ونقل، ابدأ بجني الأموال مع جيبها خلال أيام قليلة.',
    'partner.businesses': 'المؤسسات والشركات البنائية',
    'partner.businesses_desc': 'هل أنت شركة مقاولات أو صاحب ورشة بناء مهيكل؟ انضم لجيبها عبر تسجيل شركتك وابدأ بالتوفير اليوم.',
    'partner.get_listed': 'أدرج عملك الآن',
    'partner.future_building': 'مستقبل البناء والتعمير',
    'partner.future_desc': 'قم بتحميل التطبيق الآن وغير طريقة إدارتك لمواقع عملك ومشاريعك التشييدية اليوم.',

    // Stats
    'stats.title_part1': 'جيبها تنمو وتنتشر بسرعة. ',
    'stats.title_part2': 'بسرعة حقيقية فائقة.',
    'stats.tons': 'طن من المواد المسلمة',
    'stats.partners': 'شريك عملي نشط',
    'stats.employees': 'موظف ومهندس مخصص',
    'stats.cities': 'مدينة مغطاة بالكامل',

    // Footer
    'footer.tagline': "نبني البنية التحتية الرقمية المتكاملة لقطاع المقاولات والتشييد في أفريقيا. شفافية، دقة بيانات، وقوة محلية.",
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'الشروط والأحكام',

    // Map Picker Details
    'booking.select_departure': 'حدد موقع الانطلاق والتحميل',
    'booking.select_destination': 'حدد موقع الوصول والتفريغ',
    'map.instructions': 'انقر في أي مكان على الخريطة لوضع الدبوس وتحديد الموقع المستهدف',
    'map.confirm': 'تأكيد الموقع المختار',
    'map.selected_location': 'الموقع الجغرافي المحدد',
    'map.fetching': 'جاري جلب العنوان...',
    'map.use_location': 'اعتمد هذا الموقع الجغرافي',
    'hero.welcome_greet': 'مرحباً،',
    'hero.the_app': 'تطبيق جيبها للهواتف',
    'store.download': 'تحميل',
    'store.android_apk': 'تطبيق أندرويد APK',
    'store.ios_build': 'نسخة آيفون iOS',
  },
  kab: {
    // Navigation & Common (Algerian Kabylie - Taqbaylit)
    'nav.services': 'Tirura',
    'nav.materials': 'Agadir n iseɣtal n lebni',
    'nav.machinery': 'Ares Timacin',
    'nav.logistics': 'Talojistikt n udayra',
    'nav.consultancy': 'Tamsirt n Usnimer',
    'nav.company': 'Tamesselna',
    'nav.story': 'Taqsiḍt-nneɣ',
    'nav.safety': 'Taɣellist',
    'nav.newsroom': 'Axxam n tɣamsa',
    'nav.business': 'Tirmad n isebdiyen',
    'nav.register_shop': 'Sekles Taḥanut',
    'nav.work_with_us': 'Xdem yid-nneɣ',
    'nav.careers': 'Imawalen',
    'nav.support': 'Aciwen',
    'nav.help_center': 'Amasad n uciwen',
    'nav.contact': 'Nermis-aɣ-d',
    'nav.login': 'Kcem',
    'nav.signup': 'Jerred',
    'nav.dashboard': 'Agader n Tarrayt',
    'nav.delivery_history': 'Amezruy n Usiweḍ',
    'nav.my_orders': 'Tisuniyin-iw',
    'nav.shops': 'Tihuna',
    'nav.users': 'Imseqdacen',
    'nav.products': 'Farisen',
    'nav.live_tracking': 'Adas Ulaqq',
    'nav.messages': 'Izenan',
    'nav.settings': 'Isebdaden',
    'nav.sign_out': 'Ffeɣ',
    'nav.system': 'Anagraw',
    'nav.new_order': 'Tasuqt Tamaynut',
    'nav.profile': 'Udem amseqdac',
    'nav.search_placeholder': 'Nadi tisuniyin, ineddayen neɣ imsaɣen...',
    'nav.notifications': 'Inebbihen',
    'nav.live_updates': 'Ineqqisen Usriden',
    'nav.no_notifications': 'Ulac inebbihen tura',
    'nav.view_all_activity': 'Wali akk tirmad',

    // Home / Hero Section (Kabyle)
    'hero.badge': 'Asufeɣ unṣib safe & yettwaḍemmen',
    'hero.title': 'Sader Asnas n Jeebha amesni.',
    'hero.subtitle': 'Nesmed ikayaden n lebni d tsensart. Tanfala n tweb tura d tunṣibt akli! Seqdec asnas aqeṛṛan Jeebha Android i tsuniyin n tnezzut, ineqqisen n tlogistikt, d tracking d usiweḍ s tazzla.',
    'hero.spec_file': 'Isem n ufaylu',
    'hero.spec_size': 'Teɣzi n ufaylu',
    'hero.spec_version': 'Lqem lkamel',
    'hero.spec_os': 'Udan leqwan',
    'hero.btn_download': 'Sader APK Tura',
    'hero.btn_playstore': 'Google Play Store',
    'hero.download_success': 'Asader usrid n APK yebda tura!',
    'hero.welcome_title': 'D acu i tebɣid ass-a?',
    'hero.book_load': 'Heggi allal n usiweḍ',
    'hero.materials_option': 'Suneɣ Iseɣtal n lebni d ddkkan',
    'hero.logistics_option': 'Suneɣ Allalen n tlagistikt n udayra',
    'hero.register_option': 'Sekles Taḥanut am uzenzay da',
    'hero.got_it': 'Gziɣ, tanmirt!',
    'hero.become_partner': 'Uɣal d Amezday tura',
    'hero.driver_active': 'Ajerred n ineddan yermed',
    'hero.driver_sub': 'Awi idrimen ass-ass. Ḍfer tisiweḍ. Recc-ed iman-ik.',

    // Onboarding / Installation Steps (Kabyle)
    'install.guide_title': 'Amnir n Usbaddu ɣef Android',
    'install.steps_badge': '3 tsurifiyin tisehlanin',
    'install.step1_title': 'Awi Allal n usbaddu',
    'install.step1_desc': 'Asader usrid n ufaylu "jeebha.apk" isurifen iman-is. Ma yella ur ibdi ara, sseqdec tuskart n usiweḍ nnig-a.',
    'install.step2_title': 'Sireg iɣbula imexḍa',
    'install.step2_desc': 'Ruḥ ɣer Isebdaden > Taɣellist > Sireg "Asbaddu n isnasen si tsuragt ur nettwassen ara" i browser internet-inek.',
    'install.step3_title': 'Bdu asuneɣ u d-awi talwit',
    'install.step3_desc': 'Ldi afaylu i-yessadren di kra n tsinin, syin ddu s usbaddu. Snulfu-d udem-ik unṣib asrid deg usnas amesni n tabaḍnit!',
    'install.security_promise': 'AFRAG N TƔELLIST',
    'install.security_text': 'Asnas nneɣ yebna war isebdad isegranen, trackers n tnezzut, neɣ tikamiṛatin n m-iḍallan. Yettwasegrew d amafleg i ineddan d ixxamen n lebni.',

    // Downloader Dialog / Modal (Kabyle)
    'modal.install_mobile': 'Asbaddu n Jeebha ɣef Amesni',
    'modal.prod_release': 'Asufeɣ unṣib stable (v1.0.0)',
    'modal.fast_download': 'Asader usrid amɣawel yermed',
    'modal.download_desc': 'Ugadireḍ asader n jeebha.apk deg ufyal n Downloads tura',
    'modal.restart_btn': 'Ales Asader',
    'modal.step1_title': 'Asader yebda',
    'modal.step1_desc': 'Afaylu direct APK la-yessadred tura. Ma yella ur ibdi ara asader, ',
    'modal.step1_click': 'sit dagi i ulaqen tura',
    'modal.step2_title': 'Sirer iɣbula imexḍa',
    'modal.step2_desc': 'Ruḥ ɣer Isebdaden > Taɣellist > Seɣrey "Installer application mxeḍen" s browser-agi.',
    'modal.step3_title': 'Ldi & Sbaddu tura',
    'modal.step3_desc': 'Sit ɣef unebbeh n usader neɣ ldi "jeebha.apk" i d-tewwiḍ i usbaddu amɣawel tura.',
    'modal.protect_notice': 'Jeebha d tin yettwasergen d tin fermanen. Ma yella Google Play Protect yefka-yak unebbih, sit "Installer quand même" i uḍfar n tsuragt tamsefsaqt.',
    'modal.super_app': 'Asnas aselway n Tefriqt n ugafa',

    // Dashboard Customizations (Kabyle)
    'dash.title': 'Allal n Jeebha uɣal d amesni tura.',
    'dash.subtitle': 'I ufrag n tɣellist, live geofencing, d tsuniyin n lebni yettwasegrewen, ikayaden s tweb maden d iqerranen. Kcem ɣer unagraw unṣib kan seg usnas n Android.',
    'dash.specs_title': 'Udan d teɣzi n usnas',
    'dash.compat_released': 'Yeffeɣ-d di',
    'dash.compat_size': 'Teɣzi n ufaylu',
    'dash.compat_os': 'Anagraw n Android Required',
    'dash.compat_cpu': 'Aglam CPU',
    'dash.compat_perm': 'Tisuragin',
    'dash.compat_perm_val': 'Adas ulaqq, Takamiṛat',
    'dash.compat_safe': 'Yettwaḍmen d aferman',
    'dash.compat_safe_desc': 'Kull afaylu d lqem yezmel s tuffɣa tustant i usireg amellal d ufrag n isebdayen di tilkin n lebni akk.',
    'dash.seed_hub': 'Ssuq n Demonstration yermed',
    'dash.seed_desc': 'Teseḍ tesuragt takamelt i unadi n Jeebha. Bdu asbeɣyey n ssuq tura.',
    'dash.seed_btn': 'Ales asbeɣyey n ssuq d tnezzut',

    // Booking
    'booking.departure': 'Asenfar n uf falan',
    'booking.departure_placeholder': 'Fran adas n tuffɣa',
    'booking.destination': 'Adas n usiweḍ',
    'booking.destination_placeholder': 'Fran asenfar n usiweḍ',
    'booking.searching_map': 'Nadi di tkarḍa n umaḍal...',
    'booking.efficiency_desc': 'Talojistikt tamazdayt yelhan, tamsasli d-iteddun i talwit inek.',

    // Services Landing Features
    'service.materials_delivery': 'ASIWEḌ N ISEƔTAL',
    'service.peace_of_mind': 'Lebni s talwit tamanegt lkamel',
    'service.quick_easy_title': 'Yessahal & Yemɣawal',
    'service.quick_easy_desc': 'S yiwet n tsinet deg usnas, iseɣtal ad d-awḍen ɣer tkarḍa-k ass-a. Yal amkan d yal akud.',
    'service.secure_title': 'Yettwaḍmen',
    'service.secure_desc': 'Izenzayen nneɣ ran fermanen u tisiweḍ m-iḍallan s GPS, i ufrag n tɣellist tameqqrant.',
    'service.right_price_title': 'Ayen Yelhan di ssuma',
    'service.right_price_desc': 'Ssuma tetteddu d win tefrand, yettwabeggen-d si tazzla, war isegranen imxeḍen!',
    'service.site_ready': 'Udayra i-Sbedd',

    // Become Partner & Recruitment
    'partner.become_partner_sub': 'UƔAL D AMEZDAY',
    'partner.earn_money': 'Uɣal d amrawes d uzenzay i d-isuffuɣen idrimen',
    'partner.own_boss': 'Recc-ed iman-ik',
    'partner.own_boss_desc': 'Xdem di yal akud tebɣiḍ si tnafa n taḥanut-ik, s yiwet taggezit kan ɣef telkinit.',
    'partner.easy_use': 'Yessahal i useqdec',
    'partner.easy_use_desc': 'Asnas n isebdayen Jeebha d ayen akk tesriḍ i usiweḍ n requests deg udayra-k.',
    'partner.talents': 'Imawalen d Tikli',
    'partner.talents_desc': 'Ddu yid-nneɣ deg yiwet startup tesebɣes i lebni di Tefriqt. Backed by founders n Google, Airbnb & Spotify.',
    'partner.see_openings': 'Wali tirmad d isaten',
    'partner.partners': 'Inebdayen',
    'partner.partners_desc': "Azenzay neɣ andeh n truck, bdu d-awi tiɣrad s Jeebha deg wussan furas.",
    'partner.businesses': 'Tisselniwin',
    'partner.businesses_desc': 'Tella d tamesselna n lebni neɣ asbedday n usenfar? Ddu-d ɣer Jeebha s usekles n udayra inek tura.',
    'partner.get_listed': 'Sekles tura dagi',
    'partner.future_building': 'Ineqqisen n Lebni At maya',
    'partner.future_desc': 'Sader asnas tura tamaynut i ufrag n lebni d usenfar d udayra inek ass-a.',

    // Stats
    'stats.title_part1': 'Jeebha la-tettheggi s tazzla. ',
    'stats.title_part2': 'S tazzla tameqqrant ulaqq.',
    'stats.tons': 'n tons ttwawwḍen',
    'stats.partners': 'n isebdiyen unṣiben',
    'stats.employees': 'n imseqdacen yessurufen',
    'stats.cities': 'n timdinin yettwasegrewen',

    // Footer
    'footer.tagline': "Asbeddu n uɣrab n digital i tnezzut n lebni di Tefriqt. Tasedmirt, data-driven, d win n tmurt-nneɣ.",
    'footer.privacy': 'Tabaḍnit',
    'footer.terms': 'Isebdaden',

    // Map Picker Details
    'booking.select_departure': 'Fren amkan n tuffɣa',
    'booking.select_destination': 'Fren amkan n usiweḍ n usenfar',
    'map.instructions': 'Sit di yal amkan ɣef tkarḍa i ubaddu n usenfar inek d pin',
    'map.confirm': 'Sbeddet Amkan agi',
    'map.selected_location': 'Amkan yettwafran',
    'map.fetching': 'La d-itelley tura...',
    'map.use_location': 'Seqdec amkan-agi',
    'hero.welcome_greet': 'Ansuf yis-wen,',
    'hero.the_app': 'ASNAS JEEBHA MOBILE',
    'store.download': 'Sader',
    'store.android_apk': 'Android APK',
    'store.ios_build': 'iOS Build',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('jeebha_lang');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('jeebha_lang', lang);
  };

  const t = (key: string): string => {
    // Fallback order: current language -> english -> key self
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
